### ISSUE TITLE
Elm App composition using Ports and Subscriptions

### ISSUE THREAD

**Issue by fkowal** [elm/core#1009]
The purpose of this issue, for me is to have a disussion, rather then look for a solution or focus on the details.
Also i am quite new to Elm and i know i am going to pose a question that kind of doesn't make sense.
I will use Application and Component in a React sense (something that has it's own state)

Question is:

> how can i embedd an Elm application inside an Elm Application :)

What do i mean by that, and where am i going with this.
When gluing Elm with a React application here is what one is supposed to do: https://github.com/cultureamp/react-elm-components
```<Elm src="elmapp.js"/>```

I am asking if/how can I get the same with elm inside elm.

-----------------------

When reading the excellent https://github.com/rtfeldman/elm-spa-example/blob/master/src/Main.elm
you can see that all the Main does wrap and proxy/delegate view/update/subscribe

I'd like to proxy the ports, and subscriptions of an embedded App, for free.

There can be a few use cases

```
import App2
-- Simple embedding of a component/application with it's own state etc
view model = [Elm [src=App2] []]

-- passing initial flags
view model = [Elm [src=App2 flags="same as with js"] []] -- here the ports and subscriptions would be proxied without any changes

-- map the ports
type Msg = App2MsgWrapper App2.Msg
view model = [Elm [src=App2 ports=App2MsgWrapper]] -- here i need to handle the passing of messages to the App2.update, giving us pretty much the same behaviour as if we using App2.view function

```

Note about > import App2
I haven't given it much through perhaps there should be no import, but rather a path './app2'
It's there mainly for typesafety

Possible benefits:
* reduce boilder plate
* i feel this could be used for lazy loading on subcomponents

**Comment by dullbananas** [comment]
Try asking about this in elm discourse

**Comment by evancz** [comment]
I think it makes sense to pursue this on https://discourse.elm-lang.org/

Want to use issues to track bugs.
