### ISSUE TITLE
Propose Char.toInt

### ISSUE THREAD

**Issue by jc00ke** [elm/core#1010]
First off, I'd like to say that I'm loving my experience with Elm. It's been challenging in a good way, and I feel like it's a fantastic language.

Yesterday I ran into a tiny rough edge while needing to validate a [bank routing number](https://en.wikipedia.org/wiki/ABA_routing_transit_number#Check_digit) using the `371 check`:

Given the routing number `111000025`, does the following check return true?
```
(3 * (d1 + d4 + d7) + 7 * (d2 + d5 + d8) + 1 * (d3 + d6 + d9)) mod 10 == 0
(3 * (1  + 0  + 0 ) + 7 * (1  + 0  + 2 ) + 1 * (1  + 0  + 5 )) mod 10 == 0
(3 + 21 + 6) mod 10 == 0
30 mod 10 == 0
```
![It's a match!](https://media.giphy.com/media/iTjhKpMF50fNS/giphy.gif)

(One thing I noticed was that, because I use a `<input type="number">` field, the `update` function will only do work when the value is a number, not when it has other characters in it. Very cool!)

Here's the implementation I landed on, and while it's totally fine, I found myself really wanting `Char.toInt` when generating the list of `Maybe Int`.

```elm
{-| Validate a routing number according to the 371 checksum:
https://en.wikipedia.org/wiki/ABA_routing_transit_number#Check_digit

The algorithm is defined as:
3(d1 + d4 + d7) + 7(d2 + d5 + d8) + 1(d3 + d6 + d9) mod 10 = 0

    validateRoutingNumber "111000025" == True
-}
validRoutingNumber : String -> Bool
validRoutingNumber routingNumber =
    let
        numbers =
          routingNumber
          |> String.toList
          |> List.map (String.fromChar >> String.toInt)
          |> integersOnly
    in
        case numbers of
          [ d1, d2, d3, d4, d5, d6, d7, d8, d9 ] ->
            let
                chunked =
                  3 * ( d1 + d4 + d7 ) +
                  7 * ( d2 + d5 + d8 ) +
                  1 * ( d3 + d6 + d9 )
            in
                ( modBy 10 chunked ) == 0

          _ ->
            False


integersOnly : List (Maybe Int) -> List Int
integersOnly numbers =
    List.map (\n ->
      case n of
         Just d -> d

         Nothing -> 0
      )
      numbers

```

To highlight the troublesome part (though quite minor):
```elm
"111000025"
|> String.toList
|> List.map (String.fromChar >> String.toInt)
|> integersOnly

-- could become, without the String to Char to Int redirection

"111000025"
|> String.toList
|> List.map Char.toInt
|> integersOnly
```

I don't have any experience with OCaml or Haskell, but I did some hooglin' (I'm so, so sorry) and found [`Data.Char.digitToInt`](https://www.haskell.org/hugs/pages/libraries/base/Data-Char.html#v%3AdigitToInt) which only serves to validate that `Char.toInt` is not the worst idea.

There's also likely a better way of accomplishing what I need to do, and I'd love to hear what those options might be. One that I just thought of would be to create a [parser](https://package.elm-lang.org/packages/elm/parser/), but I think that's a little overkill and `Char.toInt` would still be worthwhile to add.

If `Char.toInt` would be a welcome addition, I'd love to try my hand. If not, I'll keep what I have and continue enjoying Elm. Thanks for your consideration!

**Comment by evancz** [comment]
I would typically write the following code for this scenario:

```
charToInt : Char -> Int
charToInt char =
  if Char.isDigit char then
    Just (Char.toCode char - 0x30)
  else
    Nothing
```

The process for adding things to core for now is to have things go to `elm-communuty/*-extras` so that we can start to see patterns in what people want before committing to particular APIs in core.

I don't think there is a char-extra yet though, so the folks in `#elm-community` on slack can say more about how that might go.

**Comment by jc00ke** [comment]
Very helpful, thanks! I'll go poke `#elm-community` and see if there's any interest in an package.
