### ISSUE TITLE
Using foldl for filter

### ISSUE THREAD

**Issue by guarinf** [elm/core#1012]
Shouldn't filter use foldl and then reverse the filtered list (in case of long lists)? This has the benefit that we do not iterate twice over the whole list but instead iterate once over the complete list and once over the filtered list (which should be shorter).

In fact, filter should probably use a similar implementation as [foldrHelper](https://github.com/elm/core/blob/22b2d7a235003a88af4e4af58c3d0edf43684bc9/src/List.elm#L178) to optimize for short lists but instead of calling `fold fn acc (reverse r4)` for long lists it should call `reverse (fold fn acc r4)`

**Comment by evancz** [comment]
The implementation uses `foldr` which itself uses `foldrHelper`.

Other things might be faster, but we'd want to do profiling on performance and then think about the impact on asset size.
