### ISSUE TITLE
Runtime error when trying to kill a task several times

### ISSUE THREAD

**Issue by gaku-sei** [elm/core#1015]
Calling the function `Task.kill` on the pid of an already killed task will sometimes trigger a runtime error; `Cannot read property '$' of null` in the `_Scheduler_kill` function.

```js
function _Scheduler_kill(proc)
{
	return _Scheduler_binding(function(callback) {
		var task = proc.f;
		if (task.$ === 2 && task.c) // <- throw the error here, task being null
		{
			task.c();
		}

		proc.f = null;

		callback(_Scheduler_succeed(_Utils_Tuple0));
	});
}
```

Even if killing several times the same task is probably not the best thing to do (...), Elm could add some guard (additionally to a warning message?) here to avoid a runtime error to be thrown. Like the following:

```js
function _Scheduler_kill(proc)
{
	return _Scheduler_binding(function(callback) {
		var task = proc.f;
                 if (task == null) // <- check whether task is null or undefined
                 {
                         console.warning('The task with pid ?? cannot be found, [already killed/complete]'); // <- optional warning
                         return;
                 }

		if (task.$ === 2 && task.c)
		{
			task.c();
		}

		proc.f = null;

		callback(_Scheduler_succeed(_Utils_Tuple0));
	});
}
```

**Comment by gaku-sei** [comment]
My bad, a similar issue is already opened here: https://github.com/elm/core/issues/955

**Comment by harrysarson** [comment]
@gaku-sei the folk who maintain elm really do not mind (or even encourage) duplicate issues so is not your bad at all 😄
