### ISSUE TITLE
Use narrower types for Dict.diff and Dict.intersect

### ISSUE THREAD

**Issue by sandeep-datta** [elm/core#1020]
Hi aren't the `Dict.intersect` and  `Dict.diff` methods using a `Dict` when a `List` would suffice (and be preferable since it is a narrower type (with less state))? 

For example ...
`intersect : Dict comparable v -> Dict comparable v -> Dict comparable v`
could have been ...
`intersect : Dict comparable v -> List comparable -> Dict comparable v` 
and ...
`diff : Dict comparable a -> Dict comparable b -> Dict comparable a`
could have been ...
`diff : Dict comparable a -> List comparable -> Dict comparable a`.  

This also has the added benefit that ...

1) You'd be able to intersect and diff a Dict with a plain List. 
2) The user knows from the type signature the values from the other dict are not going to be used (no need to read the documentation).

I guess this argument also applies to Set?

**Comment by Erudition** [comment]
huh? If I'm working with `Dict`s and I want an intersection, I want to intersect two `Dict`s. Not a `Dict` and a `List` that I have to pull from somewhere (or do `Dict.toList` every time, then deal with a list of tuples somehow?). Same if I want to find the difference between two `Dict`s. 

The `Set` example is perfect - `Set` is practically made for operations like `union`, `intersect` and `diff` - ideally you switch away from List when you'll be doing these; `Set` is to be considered more primitive than `List` (Set has no ordering), not less. Why would you go up to the level of List just to combine or compare Sets? That's kinda like turning two `Int`s into `Float`s just to subtract them and return an `Int`.

**Comment by evancz** [comment]
It is quite common to use `Dict.intersect`, `Dict.union`, and `Dict.diff` when working with a bunch of dictionaries.

For example, in the compiler, I have a dictionary of imported files and I have a dictionary of files I have already visited. From there, I can use something like `Dict.diff` to figure out which imported files need to be visited.

This is the more common case in functional programming in my experience, but I have definitely ran into scenarios where I actually want to diff with a set or list instead.

Whatever the API is, it will be possible to do something like `Dict.fromList (List.map (\x -> (x, ())) list` to get a dictionary, `Dict.keys dict` to get a list, etc. So I think the current API makes the most sense in that it appears to be the most commonly desired API in practice. At least according to my experience and observations so far!
