### ISSUE TITLE
String.length should mention it counts UTF-16 code units

### ISSUE THREAD

**Issue by malaire** [elm/core#1047]
Documentation of `String.length` should mention that it returns length as number of UTF-16 code units.

Or alternatively perhaps the note at `String` type which says "Strings are not lists of characters." should be expanded to say "Strings are not lists of characters, but lists of UTF-16 code points." or something like that.

**Comment by showell** [comment]
I think the correct terminology is "UTF-16 code units", not "UTF-16 code points."  Or you could say "Unicode code points encoded with UTF-16".

**Comment by evancz** [comment]
Tracked by the PR
