### ISSUE TITLE
How can I number to string

### ISSUE THREAD

**Issue by imxingquan** [elm/core#1051]
How can I number to string, Which use function

**Comment by BrianHicks** [comment]
hi! You probably want [`String.fromFloat`](https://package.elm-lang.org/packages/elm/core/latest/String#fromFloat) or [`String.fromInt`](https://package.elm-lang.org/packages/elm/core/latest/String#fromInt) depending on what kind of number you have.

You will probably get a better response for future questions by asking in the Elm Slack—you can register at https://elmlang.herokuapp.com/. I just happened to see this while doing something else 😄 Hope that helps!
