### ISSUE TITLE
Simplify case statements in Dict (moveRedLeft/moveRedRight)

### ISSUE THREAD

**Issue by showell** [elm/core#1053]
Maybe I am missing something here, but this case statement in `moveRedLeft` seems unnecessary and confusing, as both branches produce the same value.  (It appears that we always make the parent black and the two children red, without otherwise changing the tree.).

``` 
    RBNode_elm_builtin clr k v (RBNode_elm_builtin lClr lK lV lLeft lRight) (RBNode_elm_builtin rClr rK rV rLeft rRight) ->
      case clr of
        Black ->
          RBNode_elm_builtin
            Black
            k
            v
            (RBNode_elm_builtin Red lK lV lLeft lRight)
            (RBNode_elm_builtin Red rK rV rLeft rRight)

        Red ->
          RBNode_elm_builtin
            Black
            k
            v
            (RBNode_elm_builtin Red lK lV lLeft lRight)
            (RBNode_elm_builtin Red rK rV rLeft rRight)
```

And then there is, of course, similar code in `moveRedRight`.  I assume this code is correct and has no performance implications, but I found it confusing to read.  I'm mostly curious why it's written that way, so I'm filing the issue more to see the commentary than necessarily asking for a patch.

@Skinney I believe you added this code:

https://github.com/elm/core/commit/a2ae7fcc30bd1ca2d5c732f98f61e4fd1f7b288b

**Comment by Skinney** [comment]
You're right, this could be simplified. However, the code doesn't exist in the latest suggested improvements to the code: https://github.com/elm/core/pull/1033

**Comment by showell** [comment]
Thanks for the quick response.  I'll close this and check out the other PR.
