### ISSUE TITLE
== raises an exception when Json.Encode.Values are not equal below the first level

### ISSUE THREAD

**Issue by BrianHicks** [elm/core#1058]
As in #1057, I expect this also happens on `Json.Decode.Values`—I can demonstrate it in my production code but `Json.Encode.Value` was simpler to make into an SSCCE.

[Code on Ellie](https://ellie-app.com/727BMSGJ5sRa1) (reproduced below):

```elm
module Main exposing (main)

import Html exposing (text)
import Json.Encode exposing (Value, null, object)


value1 : Value
value1 =
    object [ ( "field", null ) ]


wrap : Value -> Value
wrap wrapped =
    object [ ( "wrapper", wrapped ) ]


main =
    Html.text (Debug.toString (wrap value1 == value1))
```

I expected this to print "False" but it crashed instead.

It appears that `_Utils_eqHelp` checks if either value is `null` but not if they are `undefined`. Then it tries to access a value like `undefined[field]`, which raises an exception.

**Comment by avh4** [comment]
> I expect this also happens on Json.Decode.Values

FYI, `Json.Decode.Value` is simply a type alias to `Json.Encode.Value`

**Comment by BrianHicks** [comment]
Yep, I know! That's why I expect it will happen on either, but I just wanted to be up front about which I tested with 😄

**Comment by evancz** [comment]
Equality is not supported for `Json.Encode.Values` for a variety of reasons. I talk about that a bit in #1057. It can also crash if the value contains a function. The long term fix is that "trying to use equality on JS values should be a type error".
