### ISSUE TITLE
Maybe the pad functions in String should be removed?

### ISSUE THREAD

**Issue by dullbananas** [elm/core#1083]
pad, padLeft, and padRight are probably not used very often and should be moved to String.Extra. They are mostly useful in terminal environments, not so much in browser

**Comment by rlefevre** [comment]
What evidence do you have?

`padLeft` at least is very useful to format zero padded integers (for example two digits month or day number).

**Comment by dullbananas** [comment]
Are there any other use cases for the pad functions? If not, this function could be implemented:

```elm
paddedFromInt : Int -> Int -> String
paddedFromInt digits =
    fromInt >> padLeft digits '0'
```

**Comment by dullbananas** [comment]
Usage:

```elm
paddedFromInt 5 32 == "00032"
```

**Comment by rlefevre** [comment]
I'm not sure what's your point.

This would replace a very versatile function by a limited single use case one whose signature and implementation is not simpler. 

Any other use case would be ignored or would require a minor or major update to `elm/core`, and after a while, you would be back to `padLeft` to handle most use cases with a single generic function.
