### ISSUE TITLE
Runtime exception in compiled elm script

### ISSUE THREAD

**Issue by snatvb** [elm/core#1086]
![image](https://user-images.githubusercontent.com/1572963/82133060-a76ae580-97ef-11ea-9e58-7ac72e1461da.png)
Hello, I found this when I was tried change url(redirect) without "/", I forgot added that and I got exception in elm script

**Comment by snatvb** [comment]
https://github.com/snatvb/employee-journal/tree/runtime-broken

https://github.com/snatvb/employee-journal/blob/runtime-broken/src/View/Home.elm#L63
https://github.com/snatvb/employee-journal/blob/runtime-broken/src/Main.elm#L87

**Comment by rlefevre** [comment]
What did you use to change the URL? 

If it was [`Browser.Navigation.pushUrl`](https://package.elm-lang.org/packages/elm/browser/latest/Browser-Navigation#pushUrl), it would be better to open the bug in the corresponding library:
https://github.com/elm/browser/issues

**Comment by snatvb** [comment]
Yes, you are right @rlefevre
