### ISSUE TITLE
String.lines "" returns [""]

### ISSUE THREAD

**Issue by smucode** [elm/core#1120]
Hello 👋 . The docs for `String.lines` say: 

> Break a string into lines, splitting on newlines.
> lines "How are you?\nGood?" == ["How are you?", "Good?"]

Which causes me to be very confused about this behavior:

```
> String.lines ""
[""] : List String
```

Just a bug, or is there some rationale behind this?

**Comment by smucode** [comment]
Thinking of it, it kinda makes sense 😅

**Comment by dullbananas** [comment]
That should be added as an example in the docs
