### ISSUE TITLE
Child elements not added to <template> elements

### ISSUE THREAD

**Issue by cdfa** [elm/core#1136]
Elm fails to construct HTML `<template>` elements, probably because you're supposed to call `appendChild` and such on the element's `content` property instead of the element itself.

Example:
```elm
import Html exposing (..)

view =
	node "template" [] [
		p [] [ text "Test" ]
	]
```

This will result in a `<template>` element with an empty `#document-fragment` in Firefox (109.0.1). In Chrome (110.0.5481.100) the `p` gets added outside of the `#document-fragment`, which isn't right either.

**Comment by lue-bird** [comment]
Might be more accurate to open this issue in [elm/virtual-dom](https://github.com/elm/virtual-dom) or [elm/html](https://github.com/elm/html) instead of `elm/core`

**Comment by cdfa** [comment]
Ah, I forgot that elm/virtual-dom also contained kernel code. I will reopen the issue there. Thanks :)
