### ISSUE TITLE
String.toInt "0x" == Ok NaN

### ISSUE THREAD

**Issue by zwilias** [elm/core#949]
Full list of edge-cases:

https://ellie-app.com/R9mPnktLa1/0

## Current problematic

| Expression          | 0.18     | master     |
|---------------------|----------|------------|
| `String.toInt "0x"` | `Ok NaN` | `Just NaN` |

## Fixed on master

| Expression         | 0.18     | master     |
|--------------------|----------|------------|
| `String.toInt "+"` | `Ok NaN` | `Nothing`  |
| `String.toInt "-"` | `Ok NaN` | `Nothing`  |

<details>
 <summary>Edge-cases that behave correctly</summary>

| Expression          | 0.18        | master     |
|---------------------|-------------|------------|
| `String.toInt "0X"` | `Err "..."` | `Nothing`  |
| `String.toInt "0o"` | `Err "..."` | `Nothing`  |
| `String.toInt "0O"` | `Err "..."` | `Nothing`  |
| `String.toInt "0b"` | `Err "..."` | `Nothing`  |
| `String.toInt "0B"` | `Err "..."` | `Nothing`  |

</details>

**Comment by evancz** [comment]
Do you mind adding what the output is in each case? I do not understand the headers right now.

**Comment by zwilias** [comment]
Swapped thing around so the actual issue is on top, with output from 0.18 and the changes on the master branch included. Does this work better for you?

**Comment by rtfeldman** [comment]
These all give me `Nothing` on 0.19; I can't reproduce any of them anymore!!
