### ISSUE TITLE
Provenance of List type in Default Imports

### ISSUE THREAD

**Issue by frou** [elm/core#965]
The Default Imports are documented as including:

```elm
import List exposing (List, (::))
```

But, in the `List.elm` file, there is no `type List = `

...so should the documentation instead say the following?

```elm
import List exposing ( (::) )
```

...or should a "dummy" type definition for `List` be added to `List.elm`, similar to these which already exist in their respective files:

```elm
type Int = Int -- NOTE: The compiler provides the real implementation.
type Float = Float -- NOTE: The compiler provides the real implementation.
type Char = Char -- NOTE: The compiler provides the real implementation.
type String = String -- NOTE: The compiler provides the real implementation.
```

**Comment by evancz** [comment]
I would like to expose it from `List`, but for complicated reasons within the compiler, it is hard to do that. I don't think the current code can change, and I don't think the docs should be made more complex to account for a thing that is likely to go away in the future. So I think the current balance is best.

**Comment by Razzeee** [comment]
> to account for a thing that is likely to go away in the future. 

Means that it will get exposed at some point?
