### ISSUE TITLE
Regex: no multiline option

### ISSUE THREAD

**Issue by jtrunick** [elm/core#971]
A regex like this is not possible as multiline is not supported.
    Regex.regex "/^.*$/gm"

Why is this left out, and what is the workaround?

**Comment by evancz** [comment]
Can you ask around on https://discourse.elm-lang.org/ or chat with someone on http://elmlang.herokuapp.com/ to get advice about the particular thing you want to accomplish? If it can be gotten down to an http://sscce.org/ that demonstrates the thing that's lacking, open a new issue with all the relevant info on https://github.com/elm/regex
