### ISSUE TITLE
Is there a way to use the elm lang's syntax but to run my own js code?

### ISSUE THREAD

**Issue by jshrt** [elm/core#972]
Hello,

I would like to be able to use a little js library that we are working on with the luxuries of elm-lang's type of syntax.
Example:
I want to be able to do:
```
Model = ...
```
in the "elm-lang" like syntax but run my javascript:
```
const model = lib.Model({})
```

My knowledge is limited and I plan to learn as I go, so any advice is appreciated. Also, I do not know if this is the right place to ask but where else right.

Thanks

**Comment by evancz** [comment]
Hi there :) Elm is not really designed for this use case. If you want to make direct calls back and forth, there are other languages that will work a lot better. If you just want different syntax, projects like CoffeeScript may give you more what you are looking for.

Anyway, I recommend asking questions like this on [the Elm Slack](http://elmlang.herokuapp.com/) where there are tons of folks who can help. Issues are more for specific bugs.

**Comment by jshrt** [comment]
@evancz Thanks!
