### ISSUE TITLE
More flexible functions that work with the `number` type.

### ISSUE THREAD

**Issue by rupertlssmith** [elm/core#978]
Whilst upgrading typed-svg to 0.19, I have a lot of functions like this to upgrade:

```
accelerate : number -> Attribute msg
accelerate rate =
    attribute "accelerate" <| toString rate

```

But without the `toString` function there appears to be no way to convert `number -> String`.

This could be solved by adding either:

String.fromNumber : number -> String

or perhaps better:

Basics.toFloat : number -> Float

The advantage of this is that in situations where an `Int` or `Float` is needed, the typing can be kept looser, which means that the compiler will not force the caller to convert arguments with `toFloat`.

If I change the type of accelerate to `Float -> Attribute msg' which is what I will have to do, it will likely break some existing code and require `toFloat`s to be inserted. Its not terrible but could potentially be smoother.

**Comment by evancz** [comment]
Part of the move to `String.fromInt` and `String.fromFloat` is that you now get type errors if you make a change that can change the visuals. I get that it'd be neat for the upgrade process, but I think after that, it would not be better overall.

**Comment by rupertlssmith** [comment]
Fair enoug, I will change all the API signatures to accept `Float` instead of `number`.
