### ISSUE TITLE
Changelog file is outdated

### ISSUE THREAD

**Issue by andys8** [elm/core#991]
The current information in the changelog is outdated. It includes `0.15` which is likely to be irrelevant for developers today. I'd propose to delete the file (will be in git history anyway) or add links to other changelog files that contain information relevant to `core`.

https://github.com/elm/core/blob/master/changelog.md

**Comment by alexanderkiel** [comment]
Same here. I can't find a Changelog for 1.0.5.

**Comment by evancz** [comment]
Removed the file. Thanks for the report!
