### ISSUE TITLE
Repl error

### ISSUE THREAD

**Issue by nagayev2002** [elm/core#994]
I installed elm yesterday.
Run elm repl and saw:
`-- HTTP PROBLEM ----------------------------------------------------------------

The following HTTP request failed:

    <https://package.elm-lang.org/all-packages>

Here is the error message I was able to extract:

    HttpExceptionRequest Request { host = "package.elm-lang.org" port = 443
    secure = True requestHeaders =
    [("User-Agent","elm/0.19.0"),("Accept-Encoding","gzip")] path =
    "/all-packages" queryString = "" method = "GET" proxy = Nothing rawBody =
    False redirectCount = 10 responseTimeout = ResponseTimeoutDefault
    requestVersion = HTTP/1.1 } (InternalException (HandshakeFailed (Error_Misc
    "Network.Socket.recvBuf: resource vanished (Connection reset by peer)")))
`

**Comment by everystone** [comment]
`Connection reset by peer` indicates its a network issue, try opening https://package.elm-lang.org/all-packages in your browser and verify that it loads.

**Comment by nagayev2002** [comment]
@everystone I tried it.
Connection error.
I live in Russia,maybe ip was blocked by goverment.
