### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by nagayev2002** [elm/core#995]
Parse Error:
`Basics_pi=1`
Message:
-- PARSE ERROR ------------------------------------------------------------- elm

Something went wrong while parsing repl_value_7's definition.

4| repl_value_7 =
5|   Basics_pi=1
     ^
I was expecting to see an expression, like x or 42.
Also I got this error using Basics_e

**Comment by evancz** [comment]
I think it is because of the capital letter. Saying `basics_pi = 1` in the REPL should be fine. Not sure the goal here, but I recommend asking around for help on http://elmlang.herokuapp.com/
