### ISSUE TITLE
Possible typo (_Debug_crash vs __Debug_crash)

### ISSUE THREAD

**Issue by ondrejsevcik** [elm/core#996]
There are a few calls with `_Debug_crash` in the codebase and also with `__Debug_crash` but there is no function called with two underscores in it. I think that might be a bug.

https://github.com/elm/core/blob/de38986116bd93affc1c7a12e548d1f01be9a9f1/src/Elm/Kernel/Platform.js#L38

https://github.com/elm/core/blob/01a21650a3d9da1f0aeadd71998d37e442a64c34/src/Elm/Kernel/Debug.js#L234

**Comment by evancz** [comment]
There are some weird things in kernel code, and this does not appear to be a problem. If you can find an SSCCE that causes trouble, please open an issue with that code snippet!
