### ISSUE TITLE
When used in Electron apps, 'scope' is undefined in elm.js

### ISSUE THREAD

**Issue by puruzio** [elm/core#998]
Many Elm programmers including myself enjoy using Elm in Electron apps. Unfortunately, some of us are experiencing an error caused by the fact, unlike in normal browsers, the Electron Renderer doesn't define 'this' the way Elm expects, which causes elm.js to fail as it needs the 'window' object to be passed in as 'this'.

Is it possible to make the compiled elm.js code to receive (this || window) instead of (this) as an argument? Of course, that's just one way to solve the problem, and there could be other better ways.

More details on this issue can be found here. As always, big thank you for creating and maintaining the awesome Elm-lang!
https://stackoverflow.com/questions/52902903/cannot-read-property-elm-of-undefined-while-using-elm-0-19-in-electron/52916751#52916751

**Comment by evancz** [comment]
Is it possible to put the output from the compiler in a function such that `this` would be defined like this:

```javascript
var Elm = (function() {
  ... compiler output ...
  return this.Elm;
}());
```

We have had problems in the past supporting a wide range of JS runtime environments (i.e. different kinds of JS export conventions) so we ended up with the current design. The benefits seem to be:

1. Less code is generated for the primary users of Elm.
2. People using Elm in other places can use the trick above to make it work with whatever system they happen to be working with.

Anyway, does the code shown above work for your case?

**Comment by puruzio** [comment]
Thank you. I will give it a try.

Really appreciate your kind response on this matter as well as being such a wonderful BDFL for this excellent language!
